version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    container_name: odindb
    hostname: db
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_DB=db_odin
      - POSTGRES_USER=odin
      - POSTGRES_PASSWORD=2wsxcde3a#A
    restart: always
    networks:
      - app-network
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'odin', '-d', 'db_odin']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      - TZ=Asia/Ho_Chi_Minh
    # volumes:
    #   - /api/.env/:/app/.env
    restart: unless-stopped
    # depends_on:
    #   - db
networks:
  app-network:
    external: true
    name: app-network
    driver: bridge

volumes:
  db_data:
